apiVersion: v1
kind: Service
metadata:
  name: matrix-server-service
  labels:
    matrix-service: server

spec:
  selector:
    matrix-service: server
  # This isn't used as Ingress is doing TLS termination
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: matrix-server-http
      appProtocol: TCP
      port: 8008  # <- port that will be exposed

