apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    project: data

spec:
  selector:
    pod-project: data
  # This isn't used as Ingress is doing TLS termination
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: data-ngx
      protocol: TCP
      port: 52345  # <- port that will be exposed
      # targetPort: 3000

    # - name: anubis-data
    #   protocol: TCP
    #   port: 8080  # <- port that will be exposed
    #   targetPort: 8080
    #   # targetPort: 3000

    - name: filebrowser-webgui
      protocol: TCP
      port: 80  # <- port that will be exposed
      # targetPort: 3000

