apiVersion: v1
kind: Service
metadata:
  name: matrix-landing-page-service
  labels:
    matrix-service: webclient

spec:
  selector:
    matrix-service: webclient
  # This isn't used as Ingress is doing TLS termination
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: matrix-landing-page-http
      appProtocol: TCP
      port: 80  # <- port that will be exposed

